// Read instructions instructions folder and send me money 😒 
  import Main from './main';
  import second from './images/magdalena.jpg';
  import third from './images/sabrina.jpg';
  import fifth from './images/charli.jpg';
  import sixth from './images/ken.jpg';






const App = () => {
  const info = {
    // email:"Nate12345b@gmail.com",
      email:"shamzgilbert@gmail.com",
    // Enter your account name
    yourClname:"Nhi",  
    // clients first and last name but just first name if only 1 name
    // firstname: "Nicholas",
    // firstname: "Jack Strong",
    firstname: "Fabrizio",
    lastname: "Altobelli",
    title: "",
    // make sure to change order number // if its uk do not add /UK
    order: "23-93935",
    // Status for sending both tickets
    status: "Pending",
    // Fee paid 1 for first fee and 2 for first refundable
    feePaid:2,
    // 
    us: true,       
    // Fee amount Enter how fee you wan collect
    feeamount: 83.42,
    servicefee: 150,
    //ticket safety fee or selection required fee on standard page
    idlefee:179.01,
    // ticket face value for Ticket Details or refund claim fee
    price: 153.67,
    // for service page, previous refund plus service fee
    total:"218.13",
      // Currency 
    currency: "$",
    // /, /sent, /fee, /service /standard /nfee /copy /email /tek 
    // ask for explanation
    redirectpage: "/standard",
    // countdown timer if you like enter 1000 na 1000 minutes coundown b dat
    hour: 30,
   
    // ticket purchase date
    date: "Wed, Aug 9th 2023",
    // for standard
    disco: "017000250",
    // for standard
    date1: "Sep 5th, 2024",
    // for standard
    lineup2: "",
    lineup1: "Oasis",
    // for ticketek
      // for order number
      type: "TrustTicket",
    ordernumber:'79987450, 54553',
    // order date
        orderdate:'16 MAY 2024',
        resellers:'ARTIST PRESALE',
        resellers2:'',
        emailDets: {
          header: `received`,
          img: "/billie.jpg"
        }
  }
// from here everything's self explanatory or check line one

  const events = [ 
  // {
  //     name: "Standard Admission",
  //     title: "Charli XCX & Troye Sivan present: Sweat",
  //     time: "7:30 PM" ,
  //     day: "Wed",
  //     date: "Sep 18",
  //     location:"Scotiabank Arena",
  //     state: "Toronto, ON", 
  //     year: "2024",
  //     entry: "MOBILE ENTRY",
  //     initialSection: "-FLR",
  //     countdown: false,
  //     Generaladmission: true,
  //     startcountdown: '2024-07-12 17:30:00',
  //     initialRow: "4",
  //     image: fifth,
  //     numberOfSeats: 2,
  //     startingSeatNumber: 6,
  //     code: "J6WBXRSZ4",
  //     tixsent: 0,
  //     sentfee: false,
  //     ga: false,
  //     barcode: true,
  //     cancel: false,
  //   },
    // {
    //   name: "Standard Admission",
    //   title: "$uicideboy$ - Grey Day Tour 2024 ",
    //   time: "6:30pm" ,
    //   day: "Sat",
    //   date: "Aug 17",
    //   location:"Moody Center ATX",
    //   state: "Austin, TX", 
    //   year: "2024",
    //   entry: "GA FLOOR ENTRY",
    //   initialSection: "-FLOOR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "2",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 6,
    //   code: "J6WBXRSZ4",
    //   tixsent: 2,
    //   sentfee: false,
    //   ga: true,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Admission",
    //   title: "Karan Aujla: It Was All A Dream World Tour",
    //   time: "7:30pm" ,
    //   day: "Sat",
    //   date: "Aug 17",
    //   location:"Rogers Arena",
    //   state: "Vancouver, BC, CA", 
    //   year: "2024",
    //   entry: "MOBILE ENTRY",
    //   initialSection: "118",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "7",
    //   image: fifth,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 11,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Admission",
    //   title: "Future & Metro Boomin - We Trust You Tour",
    //   time: "8:00pm" ,
    //   day: "Sat",
    //   date: "Aug 24",
    //   location:"American Airlines Center",
    //   state: "Dallas, TX", 
    //   year: "2024",
    //   entry: "GENERAL ADMISSION",
    //   initialSection: "-PIT",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "2",
    //   image: fifth,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 9,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "American Express® Early Access",
    //   title: "Olivia Rodrigo - GUTS world tour",
    //   time: "7:30pm" ,
    //   day: "Tue",
    //   date: "Aug 20",
    //   location: "Intuit Dome",
    //   state: "Inglewood, CA", 
    //   year: "2024",
    //   entry: "MOBILE ENTRY",
    //   initialSection: "C10",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-08-11 10:30:00',
    //   initialRow: "10",
    //   image: second,
    //   numberOfSeats: 3,
    //   startingSeatNumber: 7,
    //   tixsent: 0,
    //   code: "J6WBXRSZ4",
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
  // {
  //     name: "Standard Admission",
  //     title: "Olivia Rodrigo - GUTS world tour",
  //     time: "7:30 PM",
  //     day: "Fri",
  //     date: "Aug 09",
  //     location: "Rogers Arena",
  //     state: "Vancouver, BC", 
  //     year: "2024",
  //     entry: "LOWER LEVEL SEATING",
  //     initialSection: "118",
  //     countdown: false,
  //     Generaladmission: false,
  //     startcountdown: '2024-08-06 18:30:00',
  //     initialRow: "6",
  //     image: second,
  //     numberOfSeats: 2,
  //     startingSeatNumber: 6,
  //     code: "J6WBXRSZ4",
  //     tixsent: 0,
  //     sentfee: false,
  //     ga: false,
  //     barcode: true,
  //     cancel: false,
  //   },
    // {
    //   name: "Standard Admission",
    //   title: "Olivia Rodrigo",
    //   time: "7:30pm",
    //   day: "Sun",
    //   date: "Oct 13",
    //   location: "Rod Laver Arena",
    //   state: " Melbourne", 
    //   year: "2024",
    //   entry: "LOWER LEVEL",
    //   initialSection: "7",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-08-06 18:30:00',
    //   initialRow: "DD",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 6,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Ticket",
    //   title: "Future & Metro Boomin - We Trust You Tour",
    //   time: "8:00pm" ,
    //   day: "Sat",
    //   date: "Aug 31",
    //   location:"Intuit Dome",
    //   state: "nglewood, CA", 
    //   year: "2024",
    //   entry: "GENERAL ADMISSION",
    //   initialSection: "-FLR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "2",
    //   image: fifth,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 5,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Platinum Ticket",
    //   title: "Future & Metro Boomin - We Trust You Tour",
    //   time: "8:00pm" ,
    //   day: "Fri",
    //   date: "Aug 23",
    //   location:"Frost Bank Center",
    //   state: "San Antonio, TX", 
    //   year: "2024",
    //   entry: "GENERAL ADMISSION",
    //   initialSection: "-FLR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "2",
    //   image: fifth,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 9,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // // {
    //   name: "Standard Admission",
    //   title: "Future & Metro Boomin - We Trust You Tour",
    //   time: "8:00pm" ,
    //   day: "Fri",
    //   date: "Aug 30",
    //   location:"T-Mobile Arena",
    //   state: "Las Vegas, NV", 
    //   year: "2024",
    //   entry: "MOBILE TICKET",
    //   initialSection: "20",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "8",
    //   image: fifth,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 9,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // // {
    //   name: "Standard Admission",
    //   title: "Ken Carson: Chaos Tour",
    //   time: "18:00pm" ,
    //   day: "Tue",
    //   date: "Sept 17",
    //   location: 'OVO Arena, Wembley',
    //   state: "London", 
    //   year: "2024",
    //   entry: "GENADM STANDING",
    //   initialSection: "-FLR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "2",
    //   image: sixth,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 7,
    //   code: "J6WBXRSZ4",
    //   tixsent: 2,
    //   sentfee: true,
    //   ga:false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Early Entry & Merch Package",
    //   title: "Ken Carson",
    //   time: "8:00pm" ,
    //   day: "Fri",
    //   date: "Aug 16",
    //   location: 'Roadrunner-Boston',
    //   state: "Boston, MA", 
    //   year: "2024",
    //   entry: "GENADM STANDING",
    //   initialSection: "-FLOOR1",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "2",
    //   image: sixth,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 7,
    //   code: "J6WBXRSZ4",
    //   tixsent: 1,
    //   sentfee: false,
    //   ga:true,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Admission",
    //   title: "Ken Carson: Chaos Tour",
    //   time: "8:00pm" ,
    //   day: "Tue",
    //   date: "Aug 13",
    //   location: 'History',
    //   state: "Toronto, ON", 
    //   year: "2024",
    //   entry: "GENADM STANDING",
    //   initialSection: "-FLR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "2",
    //   image: sixth,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 7,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga:false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Ticket",
    //   title: "Chris Brown - The 11:11 Tour",
    //   time: "7:30pm" ,
    //   day: "Wed",
    //   date: "Aug 7",
    //   location:"Crypto.com Arena",
    //   state: "Los Angeles, CA", 
    //   year: "2024",
    //   entry: "FLOOR LEVEL SEATING",
    //   initialSection: "FLR- 4",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "7",
    //   image: fifth,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 9,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Ticket",
    //   title: 'Niall Horan: "THE SHOW" LIVE ON TOUR 2024',
    //   time: "7:30pm" ,
    //   day: "Fri",
    //   date: "Aug 2",
    //   location: "Dos Equis Pavilion",
    //   state: "Dallas, TX", 
    //   year: "2024",
    //   entry: "MOBILE ENTRY",
    //   initialSection: "102",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-08-08 10:30:00',
    //   initialRow: "D",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 9,
    //   tixsent: 0,
    //   code: "J6WBXRSZ4",
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "American Express® Early Access",
    //   title: "Olivia Rodrigo - GUTS world tour",
    //   time: "7:30pm" ,
    //   day: "Sat",
    //   date: "Aug 10",
    //   location: "Moda Center",
    //   state: "Portland, OR", 
    //   year: "2024",
    //   entry: "MOBILE ENTRY",
    //   initialSection: "102",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-08-08 10:30:00',
    //   initialRow: "D",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 9,
    //   tixsent: 0,
    //   code: "J6WBXRSZ4",
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    //  {
    //   name: "American Express® Early Access",
    //   title: "Zach Bryan",
    //   time: "7:00pm" ,
    //   day: "Wed",
    //   date: "Jul 31",
    //   location: "Frost Bank Center",
    //   state: "San Antonio, TX", 
    //   year: "2024",
    //   entry: "MOBILE ENTRY",
    //   initialSection: "10",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-03-01 18:30:00',
    //   initialRow: "9",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 6,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Ticket",
    //   title: "Chris Brown - The 11:11 Tour",
    //   time: "7:30pm" ,
    //   day: "Sun",
    //   date: "Aug 4",
    //   location:"Footprint Center",
    //   state: "Phoenix, AZ", 
    //   year: "2024",
    //   entry: "MOBILE ENTRY",
    //   initialSection: "102",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "7",
    //   image: fifth,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 9,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // // },
    //         {
    //   name: "Standard Ticket",
    //   title: "Chris Brown - The 11:11 Tour",
    //   time: "7:30pm" ,
    //   day: "Sat",
    //   date: "Aug 3",
    //   location:"T-Mobile Arena",
    //   state: "Las Vegas, NV", 
    //   year: "2024",
    //   entry: "MOBILE ENTRY",
    //   initialSection: "5",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "D",
    //   image: fifth,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 7,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Ticket",
    //   title: "Ken Carson",
    //   time: "8:00 PM" ,
    //   day: "Sat",
    //   date: "Jul 27",
    //   location:"Showbox SODO",
    //   state: "Seattle, WA", 
    //   year: "2024",
    //   entry: "GENERAL ADMISSION",
    //   initialSection: "1",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "2",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 7,
    //   code: "J6WBXRSZ4",
    //   tixsent: 2,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    //   details_only:true,
    // },
    // //  {
    //   name: "American Express Early Access",
    //   title: "Travis Scott: Utopia - Circus Maximus World Tour",
    //   time: "7:30 PM" ,
    //   day: "Sat",
    //   date: "Jul 13",
    //   location:"Co-op Live",
    //   state: "Manchester, GB", 
    //   year: "2024",
    //   entry: "GENERAL ADMISSION",
    //   initialSection: "-PIT",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "2",
    //   image: third,
    //   numberOfSeats: 3,
    //   startingSeatNumber: 7,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    //   details_only:true,
    // },
    // {
    //   name: "Platinum Ticket",
    //   title: "SABRINA CARPENTER: SHORT N' SWEET TOUR",
    //   time: "7:00pm" ,
    //   day: "Sun",
    //   date: "Sep 29",
    //   location:"Madison Square Garden",
    //   state: "New York, NY", 
    //   year: "2024",
    //   entry: "LOWER LEVEL SEATING",
    //   initialSection: "115",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "11",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 7,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    //   details_only:true,
    // },
    // {
    //   name: "Platinum Ticket",
    //   title: "Oasis",
    //   time: "5:00 PM" ,
    //   day: "Fri",
    //   date: "Jul 4",
    //   location:"Principality Stadium",
    //   state: "Cardiff, GB", 
    //   year: "2025",
    //   entry: "MOBILE TICKET",
    //   initialSection: "-FLR",
    //   countdown: true,
    //   Generaladmission: true,
    //   startcountdown: '2025-07-03 17:30:00',
    //   initialRow: "3",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 5,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    //   details_only:true,
    // },
    // {
    //   name: "Platinum Ticket",
    //   title: "Oasis",
    //   time: "5:00 PM" ,
    //   day: "Fri",
    //   date: "Jul 25",
    //   location:"Wembley Stadium",
    //   state: "London, GB", 
    //   year: "2025",
    //   entry: "MOBILE TICKET",
    //   initialSection: "-FLR",
    //   year: 2025,
    //   countdown: true,
    //   Generaladmission: true,
    //   startcountdown: '2025-07-11 17:30:00',
    //   initialRow: "3",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 5,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    //   details_only:true,
    // },
    // {
    //   name: "Platinum Ticket",
    //   title: "Oasis",
    //   time: "3:30 PM" ,
    //   day: "Sun",
    //   date: "Jul 20",
    //   location:"Heaton Park",
    //   state: "Manchester, GB", 
    //   year: "2025",
    //   entry: "MOBILE TICKET",
    //   initialSection: "-FLR",
    //   countdown: true,
    //   Generaladmission: true,
    //   startcountdown: '2025-07-11 17:30:00',
    //   initialRow: "3",
    //   image: third,
    //   numberOfSeats: 4,
    //   startingSeatNumber: 5,
    //   code: "J6WBXRSZ4",
    //   tixsent: 4,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    //   details_only:true,
    // },
    {
      name: "Platinum Ticket",
      title: "SABRINA CARPENTER: SHORT N' SWEET TOUR",
      time: "7:00 PM" ,
      day: "Mon",
      date: "Sep 23",
      location:"Nationwide Arena",
      state: "Columbus, OH", 
      year: "2024",
      entry: "MOBILE TICKET",
      initialSection: "104",
      countdown: false,
      Generaladmission: false,
      startcountdown: '2024-07-12 17:30:00',
      initialRow: "P",
      image: third,
      numberOfSeats: 2,
      startingSeatNumber: 4,
      code: "J6WBXRSZ4",
      tixsent: 0,
      sentfee: false,
      ga: false,
      barcode: true,
      cancel: false,
      details_only:true,
    },
    // {
    //   name: "Cash App Card Presale",
    //   title: "SABRINA CARPENTER: SHORT N' SWEET TOUR",
    //   time: "7:00 PM" ,
    //   day: "Thu",
    //   date: "Sep 26",
    //   location:"Little Caesars Arena",
    //   state: "Detroit, MI", 
    //   year: "2024",
    //   entry: "LOWER LEVEL SEATS",
    //   initialSection: "109",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "11",
    //   image: third,
    //   numberOfSeats: 4,
    //   startingSeatNumber: 6,
    //   code: "J6WBXRSZ4",
    //   tixsent: 2,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    //   details_only:true,
    // },
    // {
    //   name: "Platinum Ticket",
    //   title: "SABRINA CARPENTER: SHORT N' SWEET TOUR",
    //   time: "7:00 PM" ,
    //   day: "Thu",
    //   date: "Sep 26",
    //   location:"Little Caesars Arena",
    //   state: "Boston, MA", 
    //   year: "2024",
    //   entry: "FLOOR",
    //   initialSection: "D",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "6",
    //   image: third,
    //   numberOfSeats: 3,
    //   startingSeatNumber: 7,
    //   code: "J6WBXRSZ4",
    //   tixsent: 2,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Platinum Ticket",
    //   title: "Jhené Aiko: The Magic Hour Tour",
    //   time: "7:00 PM" ,
    //   day: "Thu",
    //   date: "Jun 27",
    //   location:"TD Garden",
    //   state: "Boston, MA", 
    //   year: "2024",
    //   entry: "FLOOR",
    //   initialSection: "G",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "2",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 5,
    //   code: "J6WBXRSZ4",
    //   tixsent: 1,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Platinum Ticket",
    //   title: "Shawn Mendes Performing 'Shawn' The Album Live",
    //   time: "8:30 PM" ,
    //   day: "Fri",
    //   date: "Oct 18",
    //   location:"Brooklyn Paramount",
    //   state: "Brooklyn, NY", 
    //   year: "2025",
    //   entry: "MOBILE ENTRY",
    //   initialSection: "-FLR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "4",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 4,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Verified Resale Ticket",
    //   title: "FEID - FerxxoCalipsis Tour 2024",
    //   time: "9:00 PM" ,
    //   day: "Thu",
    //   date: "Jun 20",
    //   location:"Capital One Arena",
    //   state: "Washington, DC", 
    //   year: "2024",
    //   entry: "MOBILE ENTRY",
    //   initialSection: "-FLR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "3",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 11,
    //   code: "J6WBXRSZ4",
    //   tixsent: 1,
    //   sentfee:false,
    //   ga: false , 
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Ticket",
    //   title: "Childish Gambino - The New World Tour",
    //   time: "8:00 PM" ,
    //   day: "Mon",
    //   date: "Aug 26",
    //   location:"Barclays Center",
    //   state: "Brooklyn, NY", 
    //   year: "2024",
    //   entry: "LOWER BOWL SEATING",
    //   initialSection: "7",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "19",
    //   image: third,
    //   numberOfSeats: 3,
    //   startingSeatNumber: 4,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Cash App Card Presale",
    //   title: "Oasis",
    //   time: "3:30 PM" ,
    //   day: "Fri",
    //   date: "Jul 11",
    //   location:"Heaton Park",
    //   state: "Manchester, GB", 
    //   year: "2024",
    //   entry: "GENERAL ADMISSION",
    //   initialSection: "-FLOOR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "3",
    //   image: third,
    //   numberOfSeats: 4,
    //   startingSeatNumber: 11,
    //   code: "J6WBXRSZ4",
    //   year: 2025,
    //   tixsent: 4,
    //   sentfee: false,
    //   ga: true,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Cash App Card Presale",
    //   title: "Gracie Abrams: The Secret of Us Tour with special guest Role Model",
    //   time: "7:00 PM" ,
    //   day: "Sun",
    //   date: "Sept 8",
    //   location:"Greek Theatre-U.C. Berkeley",
    //   state: "Berkeley, CA", 
    //   year: "2024",
    //   entry: "STANDING ROOM ONLY",
    //   initialSection: "-FLOOR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "3",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 11,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: true,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Cash App Card Presale",
    //   title: "Ken & Friends - The Pop Out",
    //   time: "4:00 PM" ,
    //   day: "Wed",
    //   date: "Jun 19",
    //   location:"Kia Forum",
    //   state: "Inglewood, CA", 
    //   year: "2024",
    //   entry: "STANDING ROOM ONLY",
    //   initialSection: "-FLR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "3",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 11,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Platinum Ticket",
    //   title: "Chappell Roan",
    //   time: "19:00pm" ,
    //   day: "Tue",
    //   date: "Sept 10",
    //   location:"Eventim Apollo",
    //   state: "London, UK", 
    //   year: "2024",
    //   entry: "STANDING ROOM ONLY",
    //   initialSection: "-PIT",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "5",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 11,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: true,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Platinum Ticket",
    //   title: "Chappell Roan",
    //   time: "7:00pm" ,
    //   day: "Tue",
    //   date: "Jun 11",
    //   location:"The Norva ",
    //   state: "Norfolk, VA", 
    //   year: "2024",
    //   entry: "STANDING ROOM ONLY",
    //   initialSection: "-PIT",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "5",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 11,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: true,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Verified Resale Ticket",
    //   title: "Chappell Roan",
    //   time: "7:00pm" ,
    //   day: "Fri",
    //   date: "Jun 7",
    //   location:"KEMBA Live!",
    //   state: "Columbus, OH", 
    //   year: "2024",
    //   entry: "STANDING ROOM ONLY",
    //   initialSection: "-FLR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "5",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 11,
    //   code: "J6WBXRSZ4",
    //   tixsent: 2,
    //   sentfee: true,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Platinum Ticket",
    //   title: "Chappell Roan: The Midwest Princess Tour",
    //   time: "8:00pm" ,
    //   day: "Thu",
    //   date: "Jun 13",
    //   location:"Township Auditorium",
    //   state: "Columbia, SC", 
    //   year: "2024",
    //   entry: "STANDING ROOM ONLY",
    //   initialSection: "-FLOOR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "5",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 11,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: true,
    //   ga: true,
    //   barcode: true,
    //   cancel: false,
    // },
    //  {
    //   name: "Platinum Ticket",
    //   title: "Chappell Roan",
    //   time: "8:00pm" ,
    //   day: "Wed",
    //   date: "May 29",
    //   location:"The Sylvee",
    //   state: "Madison, WI", 
    //   year: "2024",
    //   entry: "STANDING ROOM ONLY",
    //   initialSection: "-FLR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "5",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 11,
    //   code: "J6WBXRSZ4",
    //   tixsent: 2,
    //   sentfee: true,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Platinum Ticket",
    //   title: "Chappell Roan",
    //   time: "7:30pm" ,
    //   day: "Wed",
    //   date: "Jun 5",
    //   location:"Cain's Ballroom",
    //   state: "Tulsa, OK", 
    //   year: "2024",
    //   entry: "STANDING ROOM ONLY",
    //   initialSection: "-FLOOR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "5",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 11,
    //   code: "J6WBXRSZ4",
    //   tixsent: 1,
    //   sentfee: false,
    //   ga: true,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Platinum Ticket",
    //   title: "Chappell Roan",
    //   time: "8:00pm" ,
    //   day: "Tue",
    //   date: "May 28",
    //   location:"Jacobs Pavilion at Nautica",
    //   state: "Cleveland, OH", 
    //   year: "2024",
    //   entry: "LOWER LEVEL SEATING",
    //   initialSection: "5",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "J",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 9,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    //  {
    //   name: "Platinum Ticket",
    //   title: "Lana Del Rey - One Special Night, One Special Show ",
    //   time: "7:30pm" ,
    //   day: "Thu",
    //   date: "Jun 20",
    //   location: 'Fenway Park',
    //   state: "Boston, MA", 
    //   year: "2024",
    //   entry: "FLOOR ENTRY",
    //   initialSection: "FLR-A3",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "DD",
    //   image: first,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 7,
    //   code: "J6WBXRSZ4",
    //   tixsent: 1,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    //  {
    //   name: "Platinum Ticket",
    //   title: "Chappell Roan",
    //   time: "7:00pm" ,
    //   day: "Sun",
    //   date: "Sept 15",
    //   location:"O2 Academy Glasgow",
    //   state: "Glasgow", 
    //   year: "2024",
    //   entry: "STANDING ROOM ONLY",
    //   initialSection: "STALLS",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "4",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 11,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: true,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Platinum Ticket",
    //   title: "Chappell Roan",
    //   time: "8:00 PM" ,
    //   day: "Wed",
    //   date: "Jun 12",
    //   location:"Red Hat Amphitheater",
    //   state: "Raleigh, NC", 
    //   year: "2024",
    //   entry: "GENERAL ADMISSION",
    //   initialSection: "-PIT",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "3",
    //   image: third,
    //   numberOfSeats: 3,
    //   startingSeatNumber: 11,
    //   code: "J6WBXRSZ4",
    //   tixsent:0,
    //   sentfee: true,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    //  {
    //   name: "Verified Resale",
    //   title: "Taylor Swift | The Eras Tour",
    //   time: "7:30pm" ,
    //   day: "Thu",
    //   date: "Jun 13",
    //   location: "Anfield Stadium",
    //   state: "Liverpool", 
    //   year: "2024",
    //   entry: "LOWER BOWL SEATING",
    //   initialSection: "L4",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-02-13 18:30:00',
    //   initialRow: "13",
    //   image: sixth,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 23,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: true,
    // },
    //        {
    //   name: "Verified Ticket",
    //   title: "Olivia Rodrigo",
    //   time: "19:30",
    //   day: "Fri",
    //   date: "May 24",
    //   location: "Ziggo Dome",
    //   state: "Amsterdam", 
    //   year: "2024", 
    //   entry: "STANDING ROOM ONLY",
    //   initialSection: "-PIT",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-08-31 18:30:00',
    //   initialRow: "7",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 13,
    //   code: "J6WBXRSZ4",   
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: true,
    //   barcode: true,
    //   cancel: false,
    // // },
    //      {
    //   name: "American Express® Early Access",
    //   title: "Olivia Rodrigo - GUTS world tour",
    //   time: "7:30 PM",
    //   day: "Wed",
    //   date: "Aug 7",
    //   location: "Climate Pledge Arena",
    //   state: "Seattle, WA", 
    //   year: "2024",
    //   entry: "CLUB LEVEL SEATING",
    //   initialSection: "13",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-08-04 18:30:00',
    //   initialRow: "C",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 7,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Platinum Ticket",
    //   title: "Chappell Roan",
    //   time: "7:00pm" ,
    //   day: "Fri",
    //   date: "May 24",
    //   location:"Buffalo Outer Harbor",
    //   state: "Buffalo, NY", 
    //   year: "2024",
    //   entry: "STANDING ROOM ONLY",
    //   initialSection: "-PIT",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "1",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 7,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: true,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "PlatinumTicket",
    //   title: "Chappell Roan",
    //   time: "7:30pm" ,
    //   day: "Thu",
    //   date: "May 23",
    //   location:"Brown's Island",
    //   state: "Richmond, VA", 
    //   year: "2024",
    //   entry: "GENERAL ADMISSION",
    //   initialSection: "-FLR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "2",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 7,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
   
    //       {
    //   name: "Verified Ticket",
    //   title: "Olivia Rodrigo",
    //   time: "20:00",
    //   day: "Tue",
    //   date: "Oct 1",
    //   location: "Singapore Indoor Stadium",
    //   state: "Singapore", 
    //   year: "2024", 
    //   entry: "LOWER LEVEL SEATING",
    //   initialSection: "210",
    //   countdown: true,
    //   Generaladmission: false,
    //   startcountdown: '2024-08-31 18:30:00',
    //   initialRow: "11",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 13,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Verified Resale Ticket",
    //   title: "Olivia Rodrigo",
    //   time: "19:30",
    //   day: "Thu",
    //   date: "Oct 10",
    //   location: "Rod Laver Arena",
    //   state: " Melbourne", 
    //   year: "2024",
    //   entry: "LOWER TIER",
    //   initialSection: "13",
    //   countdown: true,
    //   Generaladmission: false,
    //   startcountdown: '2024-08-08 18:30:00',
    //   initialRow: "D",
    //   image: second,
    //   numberOfSeats: 3,
    //   startingSeatNumber: 9,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    //      {
    //   name: "American Express® Early Access",
    //   title: "Olivia Rodrigo - GUTS world tour",
    //   time: "7:30pm",
    //   day: "Fri",
    //   date: "Jul 19",
    //   location: "Wells Fargo Center",
    //   state: "Philadelphia, PA", 
    //   year: "2024",
    //   entry: "LEVEL 100 SEATING",
    //   initialSection: "114",
    //   countdown: true,
    //   Generaladmission: false,
    //   startcountdown: '2024-07-18 18:30:00',
    //   initialRow: "7",
    //   image: second,
    //   numberOfSeats: 3,
    //   startingSeatNumber: 10,
    //   code: "J6WBXRSZ4",
    //   tixsent: 1,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    //  {
    //   name: "Verified Fan Onsale",
    //   title: "Taylor Swift | The Eras Tour",
    //   time: "7:30pm" ,
    //   day: "Fri",
    //   date: "Jun 21",
    //   location: "Wembley Stadium",
    //  {
    //   name: "Verified Resale Ticket",
    //   title: "Olivia Rodrigo - GUTS world tour",
    //   time: "8:00 PM",
    //   day: "Sat",
    //   date: "Jun 15",
    //   location: "Accor Arena",
    //   state: "Paris", 
    //   year: "2024",
    //   entry: "CAT 1 ENTRY",
    //   initialSection: "TIER-F",
    //   countdown: true,
    //   Generaladmission: false,
    //   startcountdown: '2024-06-14 18:30:00',
    //   initialRow: "11",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 6,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },  state: "London", 
    //   year: "2024",
    //   entry: "LOWER BOWL SEATING",
    //   initialSection: "143",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-02-13 18:30:00',
    //   initialRow: "13",
    //   image: sixth,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 10,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: true,
    // },
    //     
    //  {
    //   name: "Verified Fan Onsale",
    //   title: "Taylor Swift | The Eras Tour",
    //   time: "7:00 pm" ,
    //   day: "Fri",
    //   date: "Nov 1",
    //   location: "Lucas Oil Stadium",
    //   state: "Indianapolis, IN", 
    //   year: "2024",
    //   entry: "LOWER BOWL SEATING",
    //   initialSection: "143",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-02-13 18:30:00',
    //   initialRow: "11",
    //   image: sixth,
    //   numberOfSeats: 3,
    //   startingSeatNumber: 14,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: true,
    // },
    // {
    //   name: "Verified Resale Ticket",
    //   title: 'USHER: Past Present Future',
    //   time: "8:00 PM" ,
    //   day: "Fri",
    //   date: "Aug 23",
    //   location: 'CFG Bank Arena',
    //   state: "Baltimore, MD", 
    //   year: "2024",
    //   entry: "Upper Concourse",
    //   initialSection: "3",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-05-16 18:00:00',
    //   initialRow: "Q",
    //   image: fifth,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 8,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: true,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Verified Presale Ticket",
    //   title: "Peso Pluma: Exodo Tour",
    //   time: "8:00 PM" ,
    //   day: "Fri",
    //   date: "Jul 26",
    //   location: 'Toyota Center - TX',
    //   state: "Houston, TX", 
    //   year: "2024",
    //   entry: "MOBILE TICKET",
    //   initialSection: "A",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "3",
    //   image: third,
    //   numberOfSeats: 3,
    //   startingSeatNumber: 7,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Admission",
    //   title: "Zach Bryan",
    //   time: "7:00 PM" ,
    //   day: "Tue",
    //   date: "Aug 6",
    //   location: 'Lincoln Financial Field',
    //   state: "Philadelphia, PA", 
    //   year: "2024",
    //   entry: "GENADM",
    //   initialSection: "1",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "2",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 7,
    //   code: "J6WBXRSZ4",
    //   tixsent: 2,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Admission",
    //   title: "The Marías - The Submarine Tour",
    //   time: "8:00pm" ,
    //   day: "Fri",
    //   date: "Aug 2",
    //   location: 'The Anthem',
    //   state: "Washington, DC", 
    //   year: "2024",
    //   entry: "GENADM",
    //   initialSection: "1",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "2",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 7,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    //  {
    //   name: "Verified Presale Ticket",
    //   title: "The Marías - The Submarine Tour",
    //   time: "7:00 PM" ,
    //   day: "Tue",
    //   date: "Aug 13",
    //   location: 'The Salt Shed Outdoors (Fairgrounds)',
    //   state: "Chicago, IL", 
    //   year: "2024",
    //   entry: "MOBILE TICKET",
    //   initialSection: "1",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "4",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 7,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Ticket",
    //   title: "BILLIE EILISH: HIT ME HARD AND SOFT: THE TOUR",
    //   time: "7:00pm" ,
    //   day: "Fri",
    //   date: "Oct 11",
    //   location: 'TD Garden',
    //   state: "Boston, MA", 
    //   year: "2024",
    //   entry: "STANDING ROOM ONLY",
    //   initialSection: "-FLOOR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "3",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 3,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: true,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Ticket",
    //   title: "BILLIE EILISH: HIT ME HARD AND SOFT: THE TOUR",
    //   time: "7:00pm" ,
    //   day: "Wed",
    //   date: "Oct 9",
    //   location: 'Prudential Center',
    //   state: "Newark, NJ", 
    //   year: "2024",
    //   entry: "STANDING ROOM ONLY",
    //   initialSection: "-FLOOR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "3",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 3,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: true,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Ticket",
    //   title: "Hozier - Unreal Unearth Tour 2024",
    //   time: "8:00pm" ,
    //   day: "Fri",
    //   date: "May 31",
    //   location: 'Pine Knob Music Theatre',
    //   state: "Clarkston, MI", 
    //   year: "2024",
    //   entry: "GENERAL ADMISSION",
    //   initialSection: "-PIT",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-05-16 23:30:00',
    //   initialRow: "3",
    //   image: third,
    //   numberOfSeats: 4,
    //   startingSeatNumber: 9,
    //   code: "J6WBXRSZ4",
    //   tixsent: 1,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Admission",
    //   title: "Twenty One Pilots - The Clancy World Tour",
    //   time: "7:45pm",
    //   day: "Sat",
    //   date: "Sep 7",
    //   location: 'American Airlines Center',
    //   state: "Dallas, TX", 
    //   year: "2024",
    //   entry: "MOBILE ENTRY",
    //   initialSection: "-FLR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "3",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 10,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Admission",
    //   title: "BILLIE EILISH: HIT ME HARD AND SOFT: THE TOUR",
    //   time: "7:00pm",
    //   day: "Tue",
    //   date: "Oct 1",
    //   location: 'Scotiabank Arena',
    //   state: "Toronto, ON", 
    //   year: "2024",
    //   entry: "MOBILE ENTRY",
    //   initialSection: "118",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "4",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 10,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Verified Presale Ticket",
    //   title: "BILLIE EILISH: HIT ME HARD AND SOFT: THE TOUR",
    //   time: "7:00 PM" ,
    //   day: "Sun",
    //   date: "Sept 29",
    //   location: 'Centre Videotron',
    //   state: "Québec, QC", 
    //   year: "2024",
    //   entry: "GENERAL ADMISSION",
    //   initialSection: "-FLR",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "3",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 3,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Artist Presale",
    //   title: "BILLIE EILISH: HIT ME HARD AND SOFT: THE TOUR",
    //   time: "7:00pm",
    //   day: "Thu",
    //   date: "Oct 17",
    //   location: 'Madison Square Garden',
    //   state: "New York, NY", 
    //   year: "2024",
    //   entry: "GENERAL ADMISSION",
    //   initialSection: "-PIT",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-07-12 17:30:00',
    //   initialRow: "3",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 10,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    //     {
    //   name: "Verified Presale Tickets",
    //   title: "Magdalena Bay",
    //   time: "8:00 PM" ,
    //   day: "Fri",
    //   date: "Sep 13",
    //   location: 'First Avenue',
    //   state: "Minneapolis, MN", 
    //   year: "2024",
    //   entry: "GENERAL ADMISSION",
    //   initialSection: "-FLR",
    //   countdown: false,
    //   Generaladmission:true,
    //   initialRow: "3",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 2,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: true,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Official Platinum",
    //   title: 'Niall Horan: "THE SHOW" LIVE ON TOUR 2024',
    //   time: "7:30 PM" ,
    //   day: "Wed",
    //   date: "May 29",
    //   location: 'Hard Rock Live',
    //   state: "Hollywood, FL", 
    //   year: "2024",
    //   entry: "LOWER BOWL SEATING",
    //   initialSection: "103",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-02-15 18:00:00',
    //   initialRow: "D",
    //   image: fourth,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 6,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    
    //     {
    //   name: "Standard Ticket",
    //   title: "Laufey - Bewitched: The Goddess Tour",
    //   time: "8:00pm",
    //   day: "Tue",
    //   date: "May 7",
    //   location: 'Boch Center Wang Theatre',
    //   state: "Boston, MA", 
    //   year: "2024",
    //   entry: "ORCHESTRA SEATING",
    //   initialSection: "ORCH C",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-02-15 18:00:00',
    //   initialRow: "D",
    //   image: first,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 5,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Verified Presale Tickets",
    //   title: "Laufey - Bewitched: The Goddess Tour",
    //   time: "8:00 PM" ,
    //   day: "Wed", 
    //   date: "May 1",
    //   location: 'Massey Hall',
    //   state: "Toronto, ON", 
    //   year: "2024",
    //   entry: "LEVEL 100",
    //   initialSection: "100",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-02-15 18:00:00',
    //   initialRow: "E",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 4,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Verified Resale",
    //   title: "Taylor Swift",
    //   time: "7:00pm" ,
    //   day: "Fri",
    //   date: "Aug 9",
    //   location: "Scottish Gas Murrayfield",
    //   state: "Edinburgh, UK", 
    //   year: "2024",
    //   entry: "LOWER TIER E",
    //   initialSection: "E",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-02-13 18:30:00',
    //   initialRow: "7",
    //   image: sixth,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 9,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: true,
    // },
   
    // {
    //   name: "Verified Resale Ticket",
    //   title: "Zayn / Signing Session",
    //   time: "2:00 PM",
    //   day: "Sat",
    //   date: "May 18",
    //   location: "Kingston upon Thames",
    //   state: "London, UK", 
    //   year: "2024",
    //   entry: "GENERAL ADMISSION",
    //   initialSection: "-CD",
    //   countdown: false,
    //   Generaladmission: true,
    //   startcountdown: '2024-03-01 18:30:00',
    //   initialRow: "2",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 4,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
   
    // {
    //   name: "American Express® Early Access",
    //   title: "Olivia Rodrigo - GUTS world tour",
    //   time: "7:30pm" ,
    //   day: "Fri",
    //   date: "Aug 2",
    //   location: "Chase Center",
    //   state: "San Francisco, CA", 
    //   year: "2024",
    //   entry: "MOBILE ENTRY",
    //   initialSection: "116",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-07-31 10:30:00',
    //   initialRow: "8",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 4,
    //   tixsent: 0,
    //   code: "J6WBXRSZ4",
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "American Express® Early Access",
    //   title: "Olivia Rodrigo - GUTS world tour",
    //   time: "7:30 PM" ,
    //   day: "Fri",
    //   date: "Mar 01",
    //   location: "American Airlines Center",
    //   state: "Dallas, TX", 
    //   year: "2024",
    //   entry: "GENERAL ADMISSION",
    //   initialSection: "PIT",
    //   countdown: true,
    //   Generaladmission: true,
    //   startcountdown: '2024-03-01 18:30:00',
    //   initialRow: "3",
    //   image: second,
    //   numberOfSeats: 3,
    //   startingSeatNumber: 7,
    //   tixsent: 1,
    //   code: "J6WBXRSZ4",
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "American Express® Early Access",
    //   title: "Olivia Rodrigo - GUTS world tour",
    //   time: "7:30 PM" ,
    //   day: "Fri",
    //   date: "Mar 22",
    //   location: "Nationwide Arena",
    //   state: "Columbus, OH", 
    //   year: "2024",
    //   entry: "LEVEL 100",
    //   initialSection: "103",
    //   countdown: true,
    //   Generaladmission: false,
    //   startcountdown: '2024-03-22 18:30:00',
    //   initialRow: "E",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 7,
    //   tixsent: 0,
    //   code: "J6WBXRSZ4",
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "American Express® Early Access",
    //   title: "Olivia Rodrigo - GUTS world tour",
    //   time: "7:30 PM" ,
    //   day: "Wed",
    //   date: "Mar 06",
    //   location: "Kaseya Center",
    //   state: "Miami, FL", 
    //   year: "2024",
    //   entry: "LEVEL 100",
    //   initialSection: "106",
    //   countdown: true,
    //   Generaladmission: false,
    //   startcountdown: '2024-03-06 18:30:00',
    //   initialRow: "5",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 8,
    //   tixsent: 2,
    //   code: "J6WBXRSZ4",
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Ticket",
    //   title: "Hozier - Unreal Unearth Tour 2024",
    //   time: "7:30 PM",
    //   day: "Tue,",
    //   date: "Apr 30,",
    //   location: "Moody Center ATX",
    //   state: "TX", 
    //   year: "2024",
    //   entry: "LOWER LEVEL 100",
    //   initialSection: "106",
    //   countdown: true,  
    //   Generaladmission: false,
    //   startcountdown: '2024-04-29 18:30:00',
    //   initialRow: "C",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 6,
    //   tixsent: 0,
    //   code: "J6WBXRSZ4",
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Standard Ticket",
    //   title: "Hozier - Unreal Unearth Tour 2024",
    //   time: "7:30 PM",
    //   day: "Sun,",
    //   date: "Apr 28,",
    //   location: "Dos Equis Pavilion",
    //   state: "TX", 
    //   year: "2024",
    //   entry: "LOWER LEVEL SEATING",
    //   initialSection: "100",
    //   countdown: false,  
    //   Generaladmission: false,
    //   startcountdown: '2024-04-27 18:30:00',
    //   initialRow: "D",
    //   image: second,
    //   numberOfSeats: 3,
    //   startingSeatNumber: 4,
    //   tixsent: 0,
    //   code: "J6WBXRSZ4",
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "American Express® Early Access",
    //   title: "Olivia Rodrigo - GUTS world tour",
    //   time: "7:30 PM",
    //   day: "Wed",
    //   date: "Feb 28",
    //   location: "Moody Center ATX",
    //   state: "Austin, TX", 
    //   year: "2024",
    //   entry: "CATEGORY 2",
    //   initialSection: "107",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-03-09 18:30:00',
    //   initialRow: "H",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 7,
    //   tixsent: 0,
    //   code: "J6WBXRSZ4",
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    //         {
    //   name: "American Express® Early Access",
    //   title: "Olivia Rodrigo - GUTS world tour",
    //   time: "7:30pm" ,
    //   day: "Tue",
    //   date: "Mar 19",
    //   location: "United Center",
    //   state: "Chicago, IL", 
    //   year: "2024",
    //   entry: "LEVEL 100",
    //   initialSection: "101",
    //   countdown: true,
    //   Generaladmission: false,
    //   startcountdown: '2024-03-18 18:30:00',
    //   initialRow: "10",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 8,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0, 
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "American Express® Early Access",
    //   title: "Olivia Rodrigo - GUTS world tour",
    //   time: "7:30pm" ,
    //   day: "Wed",
    //   date: "Jul 31",
    //   location: "Delta Center",
    //   state: "Salt Lake City, UT", 
    //   year: "2024",
    //   entry: "MOBILE ENTRY",
    //   initialSection: "17",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-03-18 18:30:00',
    //   initialRow: "7",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 4,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0, 
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    //     {
    //   name: "American Express® Early Access",
    //   title: "Olivia Rodrigo - GUTS world tour",
    //   time: "7:30pm" ,
    //   day: "Tue",
    //   date: "Mar 19",
    //   location: "United Center",
    //   state: "Chicago, IL", 
    //   year: "2024",
    //   entry: "LEVEL 100",
    //   initialSection: "101",
    //   countdown: true,
    //   Generaladmission: false,
    //   startcountdown: '2024-03-18 18:30:00',
    //   initialRow: "6",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 7,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    
    
    // {
    //   name: "American Express® Early Access",
    //   title: "Olivia Rodrigo - GUTS world tour",
    //   time: "7:30 PM" ,
    //   day: "Tue",
    //   date: "Mar 12",
    //   location: "Enterprise Center",
    //   state: "St Louis, MO", 
    //   year: "2024",
    //   entry: "LEVEL 100",
    //   initialSection: "103",
    //   countdown: true,
    //   Generaladmission: false,
    //   startcountdown: '2024-03-12 18:30:00',
    //   initialRow: "L",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 4,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: false,
    // },
    // {
    //   name: "Verified Fan Onsale",
    //   title: "Taylor Swift | The Eras Tour",
    //   time: "18:00pm" ,
    //   day: "Fri",
    //   date: "Oct 18",
    //   location: "Hard Rock Stadium",
    //   state: "Miami, FL", 
    //   year: "2024",
    //   entry: "LOWER LEVEL SEATING",
    //   initialSection: "218",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-02-13 18:30:00',
    //   initialRow: "14",
    //   image: third,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 8,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   barcode: true,
    //   cancel: true,
    // },
    //     {
    //   name: "Verified Fan Onsale",
    //   title: "Taylor Swift | The Eras Tour",
    //   time: "7:00pm" ,
    //   day: "Thu",
    //   date: "Nov 14",
    //   location: "Rogers Centre",
    //   state: "Toronto, ON", 
    //   year: "2024",
    //   entry: "MOBILE ENTRY",
    //   initialSection: "A 7",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-02-31 10:00:00',
    //   initialRow: "5",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 18,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   cancel: true,
    // },
    // {
    //   name: "Verified Fan Onsale",
    //   title: "Taylor Swift | The Eras Tour",
    //   time: "19:00pm" ,
    //   day: "Fri",
    //   date: "Dec 6",
    //   location: "BC Place Stadium",
    //   state: "Vancouver, CA", 
    //   year: "2024",
    //   entry: "FLOOR",
    //   initialSection: "B6",
    //   countdown: false,
    //   Generaladmission: false,
    //   startcountdown: '2024-02-31 10:00:00',
    //   initialRow: "10",
    //   image: second,
    //   numberOfSeats: 2,
    //   startingSeatNumber: 18,
    //   code: "J6WBXRSZ4",
    //   tixsent: 0,
    //   sentfee: false,
    //   ga: false,
    //   cancel: true,
    // },
  ];
  // do not trespass //
  //
  //
  return (
      <Main info={info} events={events}/>
  );
};
export default App;
